Added sign up and login pages
KeelTech/FrontendApp pull request #2
Opened 2021-07-04 08:44 UTC by nimish-keel

2021-07-05 12:18 UTC, Pankajkeel requested changes
Create new branch & pull user changes

2021-07-05 12:18 UTC, Pankajkeel commented on dev/js/actions/commons/login.js
> +      }
Plz add else condition also if the status is not 1 or response not exist we will show some error, also ask shubh to give some error screen or toaster

2021-07-05 12:18 UTC, Pankajkeel commented on dev/js/actions/commons/login.js
> +    .then(function () {
there is no need for this ".then" you can do the same work in above then statement, you can club both dispatch in above ".then"

2021-07-05 12:18 UTC, Pankajkeel commented on dev/js/actions/commons/login.js
> +  API_POST('https://getkeel.com/api/v1/user/login', {
Please use CONSTANT for host name "https://getkeel.com/" in all api call

2021-07-05 12:18 UTC, Pankajkeel commented on dev/js/actions/commons/signup.js
> +  API_POST('https://getkeel.com/api/v1/user/signup', {
use CONSTANT

2021-07-05 12:18 UTC, Pankajkeel commented on dev/js/actions/commons/signup.js
> +      let message = 'User Signed Up Successfully';
same as above club dispatch in single ".then"

2021-07-05 12:18 UTC, Pankajkeel commented on dev/js/api/api.js
> +};
Bro Plz check your PR , why all my files that I already merged to master is showing deleted in your PR, check below deleted files, it's all required

2021-07-08 10:55 UTC, closed without merging

2021-07-08 10:55 UTC, nimish-keel commented
obsolete